# Generated by Django 3.1.1 on 2020-09-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200921_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Stripe_pid',
            new_name='stripe_pid',
        ),
    ]
